const LOGIN_PAGE = "login.html";
const STUDENTS_PAGE = "students.html";

const START_ERROR_MESSAGE = "Cannot start";
const CREATE_ERROR_MESSAGE = "";
const DELETE_ERROR_MESSAGE = "";
const UPDATE_ERROR_MESSAGE = "";

export {
  LOGIN_PAGE,
  STUDENTS_PAGE,
  START_ERROR_MESSAGE,
  CREATE_ERROR_MESSAGE,
  DELETE_ERROR_MESSAGE,
  UPDATE_ERROR_MESSAGE
}
